# Generated by Django 3.2.7 on 2021-09-07 17:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=250)),
                ('venue_name', models.CharField(max_length=250)),
                ('venue_address', models.CharField(max_length=250)),
                ('venue_type', models.CharField(max_length=250)),
                ('photo_url', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('event_type', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=250)),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('starts_at', models.CharField(max_length=20)),
                ('ends_at', models.CharField(max_length=20)),
                ('main_artist', models.CharField(max_length=400)),
                ('main_genre', models.CharField(max_length=400)),
                ('is_viewable', models.BooleanField(default=True)),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(max_length=50)),
                ('category', models.CharField(default='event', max_length=50)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo_url', models.CharField(max_length=250)),
                ('place_id', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('is_viewable', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('total_ratings', models.IntegerField()),
                ('category', models.CharField(default='restaurant', max_length=50)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('rating', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.restaurant')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='EventReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('rating', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.event')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
