# Generated by Django 3.2.7 on 2021-09-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='photo_url',
            field=models.CharField(max_length=1000),
        ),
    ]
