# Generated by Django 3.2.7 on 2021-09-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20210907_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(default='event', max_length=50),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='category',
            field=models.CharField(default='restaurant', max_length=50),
        ),
    ]
