# Generated by Django 3.2.7 on 2021-09-08 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_restaurant_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='main_artist',
        ),
        migrations.RemoveField(
            model_name='event',
            name='main_genre',
        ),
    ]
