# Generated by Django 3.2.7 on 2021-09-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20210908_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='entry_price',
            field=models.CharField(max_length=50),
        ),
    ]
